name: Lint

on:
   push:
      branch: [main]
   workflow_dispatch:

jobs:
   lints:
      name: Analyse
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Export the Program
          run: cp "src/connect/main.sh" "$PREFIX/bin/connect" && chmod +x "$PREFIX/bin/connect"
        - name: Test the Program
          run: connect --verbose https://example.com/
