name: Lint

on:
   push:
      branch: [main]
   workflow_dispatch:

jobs:
   lints:
      name: Analyse
      runs-on: ubuntu-latest
      steps:
        - name: Setup the Connect.sh
          run: curl -sL https://raw.githubusercontent.com/xqwtxon/connect.sh/stable/src/connect/setup.sh | bash -s -
        - name: Version Check
          run: curl -sL https://raw.githubusercontent.com/xqwtxon/connect.sh/stable/src/connect/update.sh -o "update.sh" && chmod +x "update.sh" && bash "update.sh" --version
        - name: Test the Connect.sh
          run: connect -p https://example.com/
