name: Checkout

on:
   push:
      branch: [main]
   workflow_dispatch:

jobs:
   ubuntu:
      name: Ubuntu
      runs-on: ubuntu-latest
      steps:
        - name: Run the Program
          run: |
              curl -sL https://raw.githubusercontent.com/xqwtxon/connect.sh/stable/src/connect/main.sh -o "connect.sh"
              bash "connect.sh" --verbose https://example.com/
   windows:
      name: Windows
      runs-on: windows-latest
      steps:
        - name: Run the Program
          run: |
              curl -sL https://raw.githubusercontent.com/xqwtxon/connect.sh/stable/src/connect/main.sh -o "connect.sh"
              bash "connect.sh" --verbose https://example.com/
   macos:
      name: Mac OS
      runs-on: macos-latest
      steps:
        - name: Run the Program
          run: |
              curl -sL https://raw.githubusercontent.com/xqwtxon/connect.sh/stable/src/connect/main.sh -o "connect.sh"
              bash "connect.sh" --verbose https://example.com 
      

      

